export const AUTH = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',

  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',

  EMAIL_VER: 'EMAIL_VER',
  EMAIL_VER_SUCCESS: 'EMAIL_VER_SUCCESS',
  EMAIL_VER_FAIL: 'EMAIL_VER_FAIL',

  PASS_RECOVERY: 'PASS_RECOVERY',
  PASS_RECOVERY_SUCCESS: 'PASS_RECOVERY_SUCCESS',
  PASS_RECOVERY_FAIL: 'PASS_RECOVERY_FAIL',

  PASS_CONFIRM: 'PASS_CONFIRM',
  PASS_CONFIRM_SUCCESS: 'PASS_CONFIRM_SUCCESS',
  PASS_CONFIRM_FAIL: 'PASS_CONFIRM_FAIL',

  USER_INFO: 'USER_INFO',
  USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
  USER_INFO_FAIL: 'USER_INFO_FAIL',
};
